# Generated by Django 4.0.1 on 2022-01-21 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_alter_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(default='/menu_images/item_default.png', upload_to='menu_images/'),
        ),
    ]
